### ISSUE TITLE
ERROR IN CODE

### ISSUE THREAD

**Issue by shahidmujawar** [TanayKarve/Driving-using-motion-recogniton#5]
I DONT KNOW WHY I AM GETTING THIS ERROR

Traceback (most recent call last):
  File ".\controls.py", line 2, in <module>
    j = pyvjoy.VJoyDevice(1)
  File "C:\Python38\lib\site-packages\pyvjoy\vjoydevice.py", line 24, in __init__
    _sdk.vJoyEnabled()
  File "C:\Python38\lib\site-packages\pyvjoy\_sdk.py", line 30, in vJoyEnabled
    raise vJoyNotEnabledException()
pyvjoy.exceptions.vJoyNotEnabledException

**Comment by TanayKarve** [comment]
Checkout [this issue](https://github.com/tidzo/pyvjoy/issues/14)

**Comment by aman1243** [comment]
C:/Users/lenovo/AppData/Local/Programs/Python/Python36/python.exe e:/Driving-using-motion-recogniton-master/main.py
Traceback (most recent call last):
  File "e:/Driving-using-motion-recogniton-master/main.py", line 33, in <module>
    img,contours,hierarchy=cv2.findContours(skinMask,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE) #fit contours to hand regions
ValueError: not enough values to unpack (expected 3, got 2)
[ WARN:0] global C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-1bq9o88m\opencv\modules\videoio\src\cap_msmf.cpp (438) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback



plz solve error

**Comment by Ahmedjk4** [comment]
@TanayKarve 
solve @aman1243 error pls
